### ISSUE TITLE
关于tensorRT的问题

### ISSUE THREAD

**Issue by KevenLee** [talebolano/TensorRT-Scaled-YOLOv4#2]
1. 你的步骤中提到“下载TensorRT的开源版，在builtin_op_importers.cpp”，请问，这个 开源版本是在哪里下载？https://github.com/NVIDIA/TensorRT/tree/release/7.1 这个里面并没有 builtin_op_importers.cpp。
2. 添加相关代码后重新编译 tensorRT 么？

**Comment by talebolano** [comment]
@KevenLee 按照https://github.com/NVIDIA/TensorRT 中的步骤一步一步来，你会在TensorRT/parsers/onnx下发现builtin_op_importers.cpp
```
DEFINE_BUILTIN_OP_IMPORTER(TRT_AveragePool)
{
    return importAveragePool(ctx, node, inputs);
}
  #######在这里粘贴代码##############
} // namespace

} // namespace onnx2trt
```

**Comment by KevenLee** [comment]
还有个小问题，就是我按照 https://github.com/NVIDIA/TensorRT 里面的步骤，并且 在 TensorRT/parsers/onnx 下面添加了代码，然后编译成功了 TensorRT。我将编译出来的 lib 拷贝到 nvidia 自家提供的 tensorRTxxx.tar.gz 解压出来的文件中的 lib 下，这个作为我要使用的tensorRT？
