### ISSUE TITLE
Cannot find inference_all.cpp

### ISSUE THREAD

**Issue by imchwan** [talebolano/TensorRT-Scaled-YOLOv4#3]
First of all, thank you for sharing your works.

In your CMakeLists.txt, there is a code that requires "inference_all.cpp"
```
ADD_EXECUTABLE(inferYoloSegm inference_all.cpp )
target_link_libraries(inferYoloSegm ${OpenCV_LIBS} Tnyolo)
```

Therefore, there was an error during the build using cmake.
However, I commented it out and it seems working.

Is inference_all.cpp mandatory code?

**Comment by talebolano** [comment]
@imchwan sorry，i forget delete it
