### ISSUE TITLE
OpenCV 4 compatibility 

### ISSUE THREAD

**Issue by imchwan** [talebolano/TensorRT-Scaled-YOLOv4#4]
I installed openCV 4.0 and CV_BGR2RGB seems changed to COLOR_BGR2RGB in opencv4.

FYI, I successfully build with openCV4 by changing CV_BGR2RGB to cv::COLOR_BGR2RGB in inference.cpp

**Comment by talebolano** [comment]
@imchwan yes, there are some differences between opencv3 and opencv4
